// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Data;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20250314133030_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pending",
                            TotalAmount = 150.75m
                        },
                        new
                        {
                            Id = 2,
                            Status = "Completed",
                            TotalAmount = 299.99m
                        },
                        new
                        {
                            Id = 3,
                            Status = "Cancelled",
                            TotalAmount = 50.00m
                        },
                        new
                        {
                            Id = 4,
                            Status = "Shipped",
                            TotalAmount = 120.00m
                        },
                        new
                        {
                            Id = 5,
                            Status = "Processing",
                            TotalAmount = 75.45m
                        },
                        new
                        {
                            Id = 6,
                            Status = "Pending",
                            TotalAmount = 89.99m
                        },
                        new
                        {
                            Id = 7,
                            Status = "Completed",
                            TotalAmount = 205.99m
                        },
                        new
                        {
                            Id = 8,
                            Status = "Cancelled",
                            TotalAmount = 65.25m
                        },
                        new
                        {
                            Id = 9,
                            Status = "Shipped",
                            TotalAmount = 310.99m
                        },
                        new
                        {
                            Id = 10,
                            Status = "Processing",
                            TotalAmount = 129.50m
                        },
                        new
                        {
                            Id = 11,
                            Status = "Pending",
                            TotalAmount = 222.22m
                        },
                        new
                        {
                            Id = 12,
                            Status = "Completed",
                            TotalAmount = 432.10m
                        },
                        new
                        {
                            Id = 13,
                            Status = "Cancelled",
                            TotalAmount = 98.76m
                        },
                        new
                        {
                            Id = 14,
                            Status = "Shipped",
                            TotalAmount = 87.65m
                        },
                        new
                        {
                            Id = 15,
                            Status = "Processing",
                            TotalAmount = 190.55m
                        },
                        new
                        {
                            Id = 16,
                            Status = "Pending",
                            TotalAmount = 300.25m
                        },
                        new
                        {
                            Id = 17,
                            Status = "Completed",
                            TotalAmount = 99.99m
                        },
                        new
                        {
                            Id = 18,
                            Status = "Cancelled",
                            TotalAmount = 210.75m
                        },
                        new
                        {
                            Id = 19,
                            Status = "Shipped",
                            TotalAmount = 150.00m
                        },
                        new
                        {
                            Id = 20,
                            Status = "Processing",
                            TotalAmount = 88.88m
                        },
                        new
                        {
                            Id = 21,
                            Status = "Pending",
                            TotalAmount = 134.50m
                        },
                        new
                        {
                            Id = 22,
                            Status = "Completed",
                            TotalAmount = 250.00m
                        },
                        new
                        {
                            Id = 23,
                            Status = "Cancelled",
                            TotalAmount = 77.45m
                        },
                        new
                        {
                            Id = 24,
                            Status = "Shipped",
                            TotalAmount = 310.10m
                        },
                        new
                        {
                            Id = 25,
                            Status = "Processing",
                            TotalAmount = 210.99m
                        },
                        new
                        {
                            Id = 26,
                            Status = "Pending",
                            TotalAmount = 120.00m
                        },
                        new
                        {
                            Id = 27,
                            Status = "Completed",
                            TotalAmount = 330.75m
                        },
                        new
                        {
                            Id = 28,
                            Status = "Cancelled",
                            TotalAmount = 125.99m
                        },
                        new
                        {
                            Id = 29,
                            Status = "Shipped",
                            TotalAmount = 400.25m
                        },
                        new
                        {
                            Id = 30,
                            Status = "Processing",
                            TotalAmount = 290.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
